using ZAPI_SALES_ORDER_SRV from './external/ZAPI_SALES_ORDER_SRV.cds';

service ZAPI_SALES_ORDER_SRVSampleService {
    entity A_SalesOrder as projection on ZAPI_SALES_ORDER_SRV.A_SalesOrder
    {        key SalesOrder, SalesOrderType, SalesOrganization, DistributionChannel, OrganizationDivision, to_Item,SoldToParty, PurchaseOrderByCustomer}
    @readonly
    entity A_SalesOrderItem as projection on ZAPI_SALES_ORDER_SRV.A_SalesOrderItem
    {        key SalesOrder, key SalesOrderItem, HigherLevelItem, HigherLevelItemUsage, SalesOrderItemCategory, SalesOrderItemText, PurchaseOrderByCustomer, PurchaseOrderByShipToParty, UnderlyingPurchaseOrderItem, ExternalItemID, Material, MaterialByCustomer, PricingDate, PricingReferenceMaterial, BillingPlan, RequestedQuantity, RequestedQuantityUnit, RequestedQuantitySAPUnit, RequestedQuantityISOUnit, OrderQuantityUnit, OrderQuantitySAPUnit, OrderQuantityISOUnit, ConfdDelivQtyInOrderQtyUnit, ItemGrossWeight, ItemNetWeight, ItemWeightUnit, ItemWeightSAPUnit, ItemWeightISOUnit, ItemVolume, ItemVolumeUnit, ItemVolumeSAPUnit, ItemVolumeISOUnit, TransactionCurrency, NetAmount, TotalSDDocReferenceStatus, SDDocReferenceStatus, MaterialSubstitutionReason, MaterialGroup, MaterialPricingGroup, AdditionalMaterialGroup1, AdditionalMaterialGroup2, AdditionalMaterialGroup3, AdditionalMaterialGroup4, AdditionalMaterialGroup5, BillingDocumentDate, ContractAccount, AdditionalValueDays, ServicesRenderedDate, Batch, ProductionPlant, OriginalPlant, AltvBsdConfSubstitutionStatus, StorageLocation, DeliveryGroup, ShippingPoint, ShippingType, DeliveryPriority, DeliveryDateQuantityIsFixed, DeliveryDateTypeRule, IncotermsClassification, IncotermsTransferLocation, IncotermsLocation1, IncotermsLocation2, TaxAmount, ProductTaxClassification1, ProductTaxClassification2, ProductTaxClassification3, ProductTaxClassification4, ProductTaxClassification5, ProductTaxClassification6, ProductTaxClassification7, ProductTaxClassification8, ProductTaxClassification9, MatlAccountAssignmentGroup, CostAmount, CustomerPaymentTerms, FixedValueDate, CustomerGroup, SalesDocumentRjcnReason, ItemBillingBlockReason, SlsDocIsRlvtForProofOfDeliv, WBSElement, ProfitCenter, AccountingExchangeRate, ReferenceSDDocument, ReferenceSDDocumentItem, SDProcessStatus, DeliveryStatus, OrderRelatedBillingStatus, Subtotal1Amount, Subtotal2Amount, Subtotal3Amount, Subtotal4Amount, Subtotal5Amount, Subtotal6Amount, RequirementSegment     }    
;
}